### PR TITLE
Updated style and fonts for Val Media

### PR DESCRIPTION
**Pull request by designbyheart**

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Hi

do you have a screenshot how it looks like?

**Comment by designbyheart** [comment]
Sure. You can take a look here: 
https://drive.google.com/open?id=1UzK9LELzAcWwpn-EbvAFYd7zwjCod1O2 

Please, keep in mind that some images and videos are missing in 'new' screenshots. I worked in local environment but didn't download all uploaded videos and images.
Also, great focus was on text articles, to make them easier to read.

Whole improvements are done by introducing new files (improved-style.scss) so it can be easily isolate / used as a theme.

**Comment by DanielnetoDotCom** [comment]
So if I understand it reflects more in the article fonts correct?

why did you remove the styles from this file? plugin/Live/view/modeYoutubeLive.php

did you detect this is useless?

**Comment by designbyheart** [comment]
No, sorry for that.. That was accidental (when I was exploring how things are structured) 

In last commit, I also added a bit better look for floating video window, too. (so, no black border/background on the bottom of floating window and added some nice shadow)

**Pull request closed without merging**
