### PR TITLE
Update videoDropDownMenu.php

### PR DESCRIPTION
**Pull request by KrzysioMisio**
quotation marks are missing

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
according to the printJSString function, it will not miss the double quotes.

On what page are you seeing the missing quotes?

**Comment by KrzysioMisio** [comment]
line 44
plugin/Gallery/view/videoDropDownMenu.php 
    `<button class="btn btn-dark btn-xs dropdown-toggle" type="button" data-toggle="dropdown" title=<?php printJSString('More Options', true); ?>>`

**Comment by DanielnetoDotCom** [comment]
But what matters is the final processed page, not the source code.

For now I am not seeings reason for this

**Comment by KrzysioMisio** [comment]
ok,
go to the source of the page and see the underlining which can cause problems someday
https://demo.avideo.com/

**Comment by DanielnetoDotCom** [comment]
I see the problem, the problem is not the quote, the problem is that it is not printing the output. I will fix it now

**Comment by DanielnetoDotCom** [comment]
I guess it should be resolved now,    https://github.com/WWBN/AVideo/blob/5bf8ff6abf050b6b0f7f3fc48fe99bc3bf3d475c/plugin/Gallery/view/videoDropDownMenu.php#L44

thanks

**Comment by KrzysioMisio** [comment]
in the code is `title=<?php printJSString('More Options'); ?>>`
and it's supposed to be `title="<?php printJSString('More Options'); ?>">`

see also the big video edit button

https://user-images.githubusercontent.com/93145787/211163750-a50d8835-b159-4d0f-bb3d-ce280c632e70.mp4

**Comment by DanielnetoDotCom** [comment]
For me, it seems to be fine now

image

**Comment by KrzysioMisio** [comment]
just change width:24px to width:100% 
line 154
classes ---> .galleryVideoButtons button 
file -->  plugin/Gallery/style.css

**Comment by DanielnetoDotCom** [comment]
> style.css

where is it? this is not in the pull request

**Pull request closed without merging**
