### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by nsturtz2**

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Thanks appreciate that

**Comment by akhilleusuggo** [comment]
What is the purpose of this 2 files ?

**Comment by DanielnetoDotCom** [comment]
here https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by akhilleusuggo** [comment]
But why it is on public directory ?
Shouldn't it be on .github/ ?

**Comment by DanielnetoDotCom** [comment]
Correct, sorry I will move it

**Pull request merged**
