### PR TITLE
Update pt_BR.php

### PR DESCRIPTION
**Pull request by gbrn**
I changed some pertinent translations. And I filled in the blanks.

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
I disagree, if you want to have "Seu Email" you should have a translation $t['Your email']

**Comment by gbrn** [comment]
@DanielnetoDotCom , so i also agree with you. It was like "Your email", for me the correct one is "Email"

Seu email -> Email

image

**Comment by gbrn** [comment]
@DanielnetoDotCom , instructs me please, do I have to make the changes again? I was a little lost with the changes.

**Comment by DanielnetoDotCom** [comment]
no, does not need to make changes. 
I am not sure where you want to use ˜Your email˜, but this also requires some changes on the code and also the translation file

**Comment by gbrn** [comment]
@DanielnetoDotCom , I couldn't understand what happened. I made more than 20 suggestions in the file and none were accepted? Do I have to send a new Pull?

**Pull request closed without merging**
