### PR TITLE
Fix typos, update dependencies, and refactor.

### PR DESCRIPTION
**Pull request by Maikuolan**

### CODE REVIEW

**Comment by Maikuolan** [comment]
Commit 96d0f5b was intended to resolve the conflict between this PR and a7f83d2, but something doesn't quite look right. Hold off merging for now; Taking a closer look at it, and will reply back shortly.

**Comment by Maikuolan** [comment]
Fixed.

**Comment by DanielnetoDotCom** [comment]
Hi

what was really the thing here?

most of the modifications a saw were related to replacing declaration array() to [] and some indent code.

I did not see any huge modifications. should I look into some specific file?

**Comment by Maikuolan** [comment]
The number of lines changed may look big, but that's mostly due to the dependency updates and code-style refactoring. The others changes (the typo fixes and file deletion) are very small. There shouldn't be anything breaking here, but overall, it's a low-priority PR, because it doesn't introduce anything new or change anything significant.

In total, all typos fixed (the first two commits):

`Automaic` -> `Automatic` (Object property name).
`lenght` -> `length` (Code comment).
`You cant do this` -> `You can't do this` (Message string).
`heigth` -> `height` (CSS declaration).
`retreive` -> `retrieve` (Code comment).
`excecute` -> `Execute` (Code comment).
`Transfering` -> `Transferring` (Message string).
`untill request` -> `until requesting` (Code comment).
`You cant edit this file` -> `You can't edit this file` (Message string).
`Comming Soon` -> `Coming soon` (Translatable message string; Also updated all locale data to include this string, because most translations didn't have it yet).
`writeable` -> `writable` (Code comment).

> most of the modifications a saw were related to replacing declaration array() to [] and some indent code.

Correct. The refactoring is just code-style refactoring, utilising PHP CS Fixer (PHP CS Fixer's PSR-12 rules and PHP73Migration rules. The change from long array to short array syntax originates from the PHP73Migration rules). The changes may look big, but the changes are mostly automated changes from PHP CS Fixer (a small handful of manual changes are in there, just due to PHP CS Fixer missing a few small things, but not much). So, not an excessive amount of time spent on it (i.e., it's not a bother for me to remove those specific commits from the PR if they seem annoying due to the size and number of changes, and should be easy to do so via git rebase, or, if preferred, git cherry-pick could be used, too). :-)

Dependency updates are just utilising the composer update command (probably good to do this periodically, I think, in case of potential vulnerabilities, bugs, etc from any dependencies which we aren't aware about, which might be fixed at the upstream). It might be easier, maybe, if I remove that commit, and you can run composer update later, at your end, when convenient (less to worry about in the PR approval process, etc). Actually, I think most of the changes, even within the dependency updates, are due to the Google API client. It seems they've recently added many comments and done some similar refactoring at their own repositories recently, from what I can see.

The "useless file" mentioned in a `.DS_Store` file (Mac OSX thumbnail file) which somehow snuck into the repository at some point. I don't remember seeing it in the past, but saw it recently. Somebody must've committed accidentally somewhere, I guess. Anyway, it's not a harmful file, and won't cause problems, but is also totally useless and unnecessary for the repository, too.

Anyway, let me know what you think, and you can tell me if the PR is too much. The size of this PR is a little more ambitious than my usual PRs, although the changes aren't very significant. Because the PR is split into several different commits, it's also easy to remove any unwanted commits if needed (or, if preferred, could be written as a new PR or something like that). :-)

**Comment by DanielnetoDotCom** [comment]
Can you please resolve the conflict one last time?

I will accept the changes, but the 2 files above the change were necessary.

**Comment by Maikuolan** [comment]
Done. :-)

**Pull request merged**
