### PR TITLE
Add Korean Language Locale

### PR DESCRIPTION
**Pull request by hanyoonLDA**
KR Lang Support

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Awesome thanks

**Comment by hanyoonLDA** [comment]
@DanielnetoDotCom I want to start making premium themes for AVideo to sell on ThemeForest. I think it'll bring many new eyes to the project. Do I have your support if I move forward with this idea? (Not financial support, but just a nod of approval :) )

**Comment by DanielnetoDotCom** [comment]
Hi

Feel free to do it. :)

I recomend you to start copying some of the current themes. :)

**Comment by hanyoonLDA** [comment]
@DanielnetoDotCom Because of potential issues with merging when/if AVideo goes into new versions, would you recommend implementing themes through plugins -- like how the YouTube theme is being done currently?

**Comment by DanielnetoDotCom** [comment]
yes, always do it as a plugin. that is the best approach.

**Pull request merged**
