### PR TITLE
L10n - cz language update

### PR DESCRIPTION
**Pull request by Joelp**

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
I would like to merge it but I cannot, can you please resolve the conflicts?

image

**Comment by Joelp** [comment]
I updated branche to your master. Do you have more info about conflict? I only see this
obrazek

**Comment by DanielnetoDotCom** [comment]
I guess it is good with your version. on my side still a conflict

image

**Comment by Joelp** [comment]
Pulled the newest changes from your master. Is it OK or not for now?

**Comment by DanielnetoDotCom** [comment]
I guess it is fine now

**Pull request merged**
